[project]
name = "ai-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=5.0.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "transformers>=5.15.0",
]

[project.scripts]
ai-test = "ai_test:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
